# Generated by Django 4.0.6 on 2022-09-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
