version: "3"

services:

  backend:
    image: local:0.0.1
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/app/build"
    env_file:
      - .env
    ports:
      - "8000:8000"

  celery:
    image: local:0.0.1
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: celery -A settings worker --loglevel=INFO --pidfile=/tmp/celery.pid


  celerybeat:
    image: local:0.0.1
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: celery -A settings beat --loglevel=INFO --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid

  memcached:
    image: memcached:1.6.17
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.11.3-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

  flower:
    image: local:0.0.1
    build: .
    container_name: flower
    stdin_open: true
    tty: true
    env_file:
      - .env
    command: celery -A proj flower  --address=127.0.0.1 --port=5566


volumes:
  db_data: {}