# Generated by Django 4.0.6 on 2022-08-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_rate_base_currency_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField(max_length=10)),
                ('request_method', models.CharField(max_length=12)),
                ('query_params', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
