# Generated by Django 4.0.6 on 2022-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_rate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.CharField(choices=[('UAH', 'Hryvna'), ('USD', 'Dollar'), ('EUR', 'Euro'),
                                            ('BTC', 'Bitcoin')], max_length=3, null=True),
        ),
    ]
