# Generated by Django 4.0.6 on 2022-09-29 15:51

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_alter_rate_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='bank_avatar',
            field=models.FileField(default=1, upload_to=currency.models.source_avatar),
            preserve_default=False,
        ),
    ]
