# Generated by Django 4.0.6 on 2022-09-29 16:46

import currency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_source_bank_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='bank_avatar',
            field=models.FileField(default='bank.jpeg', upload_to=currency.models.source_avatar),
        ),
    ]
